//  Automatically Generated code  

#ifndef __EMoon_Sketch__Lightshows__
#define __EMoon_Sketch__Lightshows__

#include <stdio.h>
#include "EMoonDesign.h"
#include "Strips.h"
#include "colours.h"


void wait(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// A Lightshow in this file is a primitive
// It cannot be made up of other lightshows
// It is generally assumed to last at least 16 frames
// It covers a single pod

void rainbowSpread(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void redFade(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void gordon1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void blackFade(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void gordon2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void redRed(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void gordon3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void redGreen(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void backGreen(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void greenBlack(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void greenBlue(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void mardigras(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// edge wipes

void edgewipe0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe10(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe11(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe12(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe20(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe21(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe22(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe30(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe31(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void edgewipe32(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);




//assortment of red yellow green purple

void a0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void a7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// cascading washes in red blue and other colours

void b0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void b7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// mauve shades, blooming

void c0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void c7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// sparkle theme

void d0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void d7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// red, yellow, blue wipes and misc

void e0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void e7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


// blue theme ---------------------------------------------

void f0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void f7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


// shuffle theme ----------------------------------------


void g0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void g7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// yellow theme, spins and fades

void h0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void h7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

// aussie theme

void aus0(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus1(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus2(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus3(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus4(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus5(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus6(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void aus7(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	redsquare0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


void	my28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	my30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	wind0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	windyellow0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	windwhite0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	windwhite1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	windwhite2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	rise0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	rise1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	rise2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	redrise0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	redrise1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	redrise2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	sparkrise0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	sparkrise1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	sparkrise2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	sparkrise28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	sparkrise29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	sparkrise30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral0_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral1_0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral1_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


void	spiral2_0	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_65	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_66	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_67	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_68	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_69	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_70	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_71	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_72	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_73	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_74	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_75	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_76	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_77	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_78	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_79	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_80	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_81	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_82	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_83	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_85	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_86	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_87	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_88	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_90	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_91	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_92	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_93	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_95	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_96	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_97	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_98	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	spiral2_100	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_101	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_102	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_103	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_104	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_105	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_106	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_107	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_108	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_109	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_110	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_111	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_112	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_113	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_114	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_115	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_116	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_117	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_118	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	spiral2_119	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	field0_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	field0_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_40	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_48	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_56	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_65	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_66	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_67	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_68	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_69	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_70	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_71	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_72	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_73	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_74	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_75	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_76	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_77	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_78	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_79	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_80	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_81	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_82	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_83	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_84	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_85	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_86	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_87	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_88	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_89	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_90	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	field0_92	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_93	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	field0_95	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_96	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_97	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_98	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_99	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	field0_101	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_102	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_103	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_104	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_105	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_106	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_107	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_108	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_109	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_110	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_111	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_112	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_113	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_114	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_115	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	field0_116	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	flasher_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	flasher_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


void	tetfall0_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall0_16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	tetfall1_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_40	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_48	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_56	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_63	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	tetfall1_64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);


void	messfall1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall40	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall48	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall56	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall63	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	messfall64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	munge1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge40	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge48	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge56	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge63	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);

void	munge1_1	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_2	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_3	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_4	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_5	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_6	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_7	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_8	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_9	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_10	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_11	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_12	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_13	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_14	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_15	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_16	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_17	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_18	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_19	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_20	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_21	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_22	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_23	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_24	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_25	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_26	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_27	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_28	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_29	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_30	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_31	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_32	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_33	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_34	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_35	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_36	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_37	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_38	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_39	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_40	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_41	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_42	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_43	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_44	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_45	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_46	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_47	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_48	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_49	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_50	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_51	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_52	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_53	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_54	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_55	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_56	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_57	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_58	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_59	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_60	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_61	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_62	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_63	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_64	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_65	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_66	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_67	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_68	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_69	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_70	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_71	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_72	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_73	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_74	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_75	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_76	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_77	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_78	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_79	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_80	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_81	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_82	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_83	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_84	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_85	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_86	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_87	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_88	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_89	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_90	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_91	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_92	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_93	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_94	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_95	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_96	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_97	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_98	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_99	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_100	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_101	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_102	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_103	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_104	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_105	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_106	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_107	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_108	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_109	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_110	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_111	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_112	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_113	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_114	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_115	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_116	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_117	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_118	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_119	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_120	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_121	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_122	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_123	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_124	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_125	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_126	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_127	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_128	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_129	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_130	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_131	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_132	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_133	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_134	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_135	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_136	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_137	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_138	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_139	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_140	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_141	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_142	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_143	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_144	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_145	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_146	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_147	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_148	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_149	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_150	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_151	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_152	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_153	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_154	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_155	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_156	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_157	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_158	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_159	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_160	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_161	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_162	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_163	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_164	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_165	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_166	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_167	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_168	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_169	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_170	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_171	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_172	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_173	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_174	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_175	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_176	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_177	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_178	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_179	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_180	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_181	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_182	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_183	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_184	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_185	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_186	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_187	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_188	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_189	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_190	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_191	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);
void	munge1_192	(eMoonFrame f, eMoonFrame duration, Adafruit_NeoPixel* strip);



#endif
